# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
        exclude: ^.gitlab-ci.yml
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: pretty-format-json
        args:
          - "--no-sort-keys"
          - "--autofix"
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args:
          - "-l 120"
  -   repo: https://github.com/asottile/blacken-docs
      rev: v1.12.1
      hooks:
      -   id: blacken-docs
          additional_dependencies: [black==22.6.0]
  # - repo: https://github.com/gruntwork-io/pre-commit
  #   rev: v0.1.22
  #   hooks:
  #     # - id: tflint
  #     - id: terraform-validate
  #     - id: terraform-fmt
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.0
    hooks:
      - id: terraform_fmt
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "Readme.md", "./deployment"]
