# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
        # exclude: github actions
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: pretty-format-json
        args:
          - "--no-sort-keys"
          - "--autofix"
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.10.1
  #   hooks:
  #     - id: isort
  #       name: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - "-l 120"
  - repos:
      - repo: https://github.com/gruntwork-io/pre-commit
        rev: v0.1.17 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
        hooks:
          - id: terraform-fmt
          - id: terraform-validate
          - id: tflint
          - id: shellcheck
          - id: gofmt
          - id: golint