apiVersion: v1
kind: Secret
metadata:
  name: sagemaker-read-access-secret
  namespace: {{ .Values.deployment.namespace }}
type: Opaque
stringData:
  AWS_REGION: {{ .Values.secret.aws_region }}
  AWS_ACCESS_KEY_ID: {{ .Values.secret.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.aws_secret_access_key }}
  AWS_ROLE_NAME: {{ .Values.secret.aws_role_name }}