apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-service
  namespace: {{ .Values.deployment.namespace }}
spec:
  selector:
    app: {{ .Values.deployment.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501