kind: ConfigMap
apiVersion: v1
metadata:
  name: mlflow-config
  namespace: mlflow
data:
  ARTIFACT_S3_BUCKET: {{ .Values.artifacts.S3_BUCKET }}
  ARTIFACT_S3_KEY_PREFIX: {{ .Values.artifacts.S3_KEY_PREFIX }}
  DB_NAME: {{ .Values.DB_NAME }}
