kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.deployment.name }}-config
  namespace: {{ .Values.deployment.namespace }}
data:
  ARTIFACT_S3_BUCKET: {{ .Values.artifacts.s3_bucket }}
  ARTIFACT_S3_KEY_PREFIX: {{ .Values.artifacts.s3_key_prefix }}
  DB_NAME: {{ .Values.rds.db_name }}
