apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccount: {{ .Values.deployment.name }}-user
      containers:
        - name: {{ .Values.deployment.name }}
          securityContext: {}
          image: {{ .Values.deployment.image }}
          imagePullPolicy: Always
          env:
            - name: MLFLOW_PORT
              value: "5000"
            - name: MLFLOW_BACKEND_STORE_URI
              value: mysql://$(RDS_USERNAME):$(RDS_PASSWORD)@$(RDS_HOST):$(RDS_PORT)/$(DB_NAME)
            - name: MLFLOW_DEFAULT_ARTIFACT_ROOT
              value: s3://$(ARTIFACT_S3_BUCKET)/$(ARTIFACT_S3_KEY_PREFIX)
          command:
            - /bin/bash
            - -c
            - |
              mlflow db upgrade "mysql://${RDS_USERNAME}:${RDS_PASSWORD}@${RDS_HOST}:${RDS_PORT}/${DB_NAME}";
              mlflow server --host=${MLFLOW_HOST} --port=${MLFLOW_PORT} --backend-store-uri=mysql://${RDS_USERNAME}:${RDS_PASSWORD}@${RDS_HOST}:${RDS_PORT}/${DB_NAME} --artifacts-destination=s3://${ARTIFACT_S3_BUCKET}/${ARTIFACT_S3_KEY_PREFIX} --default-artifact-root=s3://${ARTIFACT_S3_BUCKET}/${ARTIFACT_S3_KEY_PREFIX} --serve-artifacts --static-prefix=/mlflow
          envFrom:
            - secretRef:
                name: {{ .Values.deployment.name }}-secret
            - configMapRef:
                name: {{ .Values.deployment.name }}-config
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.ingress.path }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.ingress.path }}
              port: http
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"