apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
  namespace: mlflow
type: Opaque
stringData:
  RDS_USERNAME: {{ .Values.rds.USERNAME }}
  RDS_PASSWORD: {{ .Values.rds.PASSWORD }}
  RDS_HOST: {{ .Values.rds.HOST }}
  RDS_PORT: "{{ .Values.rds.PORT }}"
