apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.deployment.name }}-user
  namespace: {{ .Values.deployment.namespace }}
  annotations: 
    eks.amazonaws.com/role-arn: {{ .Values.artifacts.s3_role_arn }}
