apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: mlflow
spec:
  selector:
    app: mlflow
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mlflow-lb
#   namespace: mlflow
# spec:
#   selector:
#     app: mlflow
#   type: LoadBalancer
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5000