airflow:
  users:
    ## define the user called "admin"  # TODO
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com
      firstName: admin
      lastName: admin
    ## define the user called "user"  # TODO
    - username: user
      password: user123
      role:
        - User
        - Viewer
      email: user@example.com
      firstName: user
      lastName: user
  usersUpdate: true
  legacyCommands: false
  image:
    repository: apache/airflow
    tag: 2.2.5-python3.8
    pullPolicy: IfNotPresent
    pullSecret: ""
    uid: 50000
    gid: 0
  executor: KubernetesExecutor
  fernetKey: "7T512UXSSmBOkpWimFHIVb8jK6lfmSAvx4mO6Arehnc=" # auslagern?
  webserverSecretKey: "THIS IS UNSAFE!"
workers:
  enabled: false
flower:
  enabled: false
postgresql:
  enabled: false
redis:
  enabled: false
externalDatabase:
  type: postgres
  host: ""
  port: ""
  database: airflow_db # auslagern?
  user: airflow_admin # auslagern?
  passwordSecret: ""
  passwordSecretKey: "postgresql-password" # auslagern?
  properties: ""
dags:
  gitSync:
    enabled: true
    repo: ""
    branch: ""
    revision: HEAD
    httpSecret: ""
    httpSecretUsernameKey: username # auslagern?
    httpSecretPasswordKey: password # auslagern?
