airflow:
  legacyCommands: false
  image:
    repository: apache/airflow
    tag: 2.2.5-python3.8
    pullPolicy: IfNotPresent
    pullSecret: ""
    uid: 50000
    gid: 0
  executor: KubernetesExecutor
  fernetKey: "7T512UXSSmBOkpWimFHIVb8jK6lfmSAvx4mO6Arehnc="
  webserverSecretKey: "THIS IS UNSAFE!"
workers:
  enabled: false
flower:
  enabled: false
postgresql:
  enabled: false
redis:
  enabled: false
externalDatabase:
  type: postgres
  host: airflow-postgres.cwnjgv0wsmee.eu-central-1.rds.amazonaws.com # TODO dynamic input
  port: 5432
  database: airflow_db
  user: airflow_admin
  passwordSecret: "airflow-db-auth"
  passwordSecretKey: "postgresql-password"
  properties: ""
dags:
  gitSync:
    enabled: true
    repo: ssh://git@github.com/seblum/Airflow_DAGs.git
    branch: main
    revision: HEAD
    sshSecret: airflow-git-ssh-secret
    sshSecretKey: gitSshKey
